### ISSUE TITLE
Nukes/antinukes

### ISSUE THREAD

**Issue by keijj0** [techannihilation/TA_O#1031]
Last night i looked up nuke and anti stockpiletimes, they utter crap atm and makes nukespam too easy.
Current values stockpiletimes are: anti 100 and nukes 120. BA has anti 90 and armnuke 120 and corenuke 180. Since labs and especially cons are so much more expensive compared to BA, nuking anyone but pure techer is easy

My solution to nuke problems would be make loaded anti and unloaded anti. increase nuke price and increase stockpiletime of tll and core nukes.

First drop anti stockpiletimes to 90, make unloaded anti half from current price and loaded anti 2x from current price. Increase nuke cost by 20 % and since tll have bigger aoe than arm and core bigger aoe than tll -> increase tll nuke stockpile to 135 and corenuke to 150.

Also mobile antinukes should be a bit cheaper and if someone could bother, make them available at every t2 lab except air

**Comment by Leggir** [comment]
It'd be interesting if the nuke bases were set to fire at will, so if playing the AI and they build a nuke it'll automatically fire. Currently playing the AI there's no reason to build anti-nuke because they never fire nukes.

**Comment by ksilversurfer** [comment]
oook i agree that sometimes overnuke is an issue

**Comment by ksilversurfer** [comment]
but it happens only late games, so you can afford many anties anyway
