### ISSUE TITLE
ARM T2 KBOT - X1 & Lightning suggestions

### ISSUE THREAD

**Issue by killfreekill** [techannihilation/TA_O#1329]
ARM T2 KBOT X-1 has old model icon in build menu. The old X1 kbot model and unit was nicer, bring it back please. The new unit can stay though as additional one. The lightning T2 kbot could be again all-terrain and not jump as now, its nerfed enough.

**Comment by skymyj** [comment]
Hey killfree. When you say nicer. You talk about model or balance? I could remplace plasma by missile or machine gun (projectile like pop up canon).

**Comment by nixtux** [comment]
He is on about model, and I also think old model is better

**Comment by killfreekill** [comment]
About the model and unit ballance as well. I would just add previous X1 and keep new X1 there as well as X2 for example.

**Comment by skymyj** [comment]
I propose the new AK mech with : 
- better stats for main weapon. (decrease reload)
- New missile launcher
- Personnal Blue shield

![image](https://user-images.githubusercontent.com/2990630/44199118-85888e80-a143-11e8-8af7-73401f379ade.png)

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/44202601-bd480400-a14c-11e8-9e1d-fa797071c1ce.png)
