### ISSUE TITLE
archnano in turtle lab

### ISSUE THREAD

**Issue by nixtux** [techannihilation/TA_O#274]
Why in turtle lab, looks like it does not fit at all

**Comment by skymyj** [comment]
Ahah. You should see T2 vehicle lab.

Now, Archnano is all terrain and amphibious. His place is justified

**Comment by nixtux** [comment]
So a spider in a turtle lab looks like right? So lemons growing on an apple tree is fine?

**Comment by skymyj** [comment]
I like your joke. Makes me smile.
It's why I posted #22. We need veh, air, and turtoise engineerer. We need cons copter too if you want them survive on this mode.

**Comment by nixtux** [comment]
As I've said before your here with the wrong attitude it seems.

**Comment by nixtux** [comment]
Sorry got the wrong end if the stick

**Comment by ksilversurfer** [comment]
TLL turtles needs in lab resurrection turtle bot, **not combat engineer**

**Comment by skymyj** [comment]
Proposition for engineer turtle and new T2 engineer for Kbot. (ATM, the archnano is too strong with all terrain and speed).
![sans titre](https://user-images.githubusercontent.com/2990630/49727340-49d48000-fc70-11e8-9b82-38e38951a6fe.png)

**Comment by skymyj** [comment]
You can close it
